### ISSUE TITLE
Exception Error with ProXAS-v2.35

### ISSUE THREAD

**Issue by KonfusedKumar** [ClarkAH/ProXAS-GUI#1]
[Exception error_ProXAS-v2.35_BatchExport.txt](https://github.com/ClarkAH/ProXAS-GUI/files/4260898/Exception.error_ProXAS-v2.35_BatchExport.txt)

Not sure what I am doing wrong here. This exception error happens when I press batch export. Can you please tell me what I am doing wrong and how I could fix it?

Susmit

**Comment by ClarkAH** [comment]
This looks like it is an old version due to the way the process queue is being created. Can you tell me which version you are using? 

I think this problem was solved a while ago and relates to the angular range being different for some oscillations of the monochromator. 

I would suggest updating to the latest version and see if this still causes problems, 2,37

**Comment by ClarkAH** [comment]
I recently came across this problem again. It can happen infrequently when not using the interpolation step of the program. In theory this should now also be solved so that all the spectra have identical data ranges even without interpolation by finding the minimum oscillation range of the monochromator (not every oscillation is identical).
